//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcCv.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DbCVEntities : DbContext
    {
        public DbCVEntities()
            : base("name=DbCVEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TBL_ADMİN> TBL_ADMİN { get; set; }
        public virtual DbSet<TBL_DENEYİM> TBL_DENEYİM { get; set; }
        public virtual DbSet<TBL_EGİTİM> TBL_EGİTİM { get; set; }
        public virtual DbSet<TBL_HAKKİMDA> TBL_HAKKİMDA { get; set; }
        public virtual DbSet<TBL_İLETİSİM> TBL_İLETİSİM { get; set; }
        public virtual DbSet<TBL_SERTİFİKA> TBL_SERTİFİKA { get; set; }
        public virtual DbSet<TBL_YETENEK> TBL_YETENEK { get; set; }
        public virtual DbSet<TBL_HOBİ> TBL_HOBİ { get; set; }
        public virtual DbSet<TBL_SOSYALM> TBL_SOSYALM { get; set; }
    }
}
